#!/bin/bash
WORKING_BRANCH=$(git branch | grep '* ' | cut -d \  -f 2)
if [ "$WORKING_BRANCH" = "gh-pages" ]; then
    git commit -am "save to publish in gh-pages branch"
    git push origin gh-pages
else
    echo "You're in $WORKING_BANCH branch"
    echo "You need to pull in changes to the gh-pages branch to publish"
fi
